version: '3.8'
services:
  # PostgreSQL база данных
  postgres:
    # Используем конкретную версию вместо :latest для безопасности
    image: postgres:15.5-alpine3.18
    restart: unless-stopped
    environment:
      # Database configuration with improved security and maintainability
      POSTGRES_USER: ${POSTGRES_USER:-anime_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-anime_site_db}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
      
      # Security enhancement: Force password usage in production
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./server/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-anime} -d ${POSTGRES_DB:-anime_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - anime-network
    # Установка ограничений ресурсов для безопасности
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Redis для кеширования и сессий
  redis:
    # Используем конкретную версию вместо :latest для безопасности
    image: redis:7.2.3-alpine3.18
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-redispass}
    volumes:
      - redisdata:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - anime-network
    # Установка ограничений ресурсов для безопасности
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M

  # Frontend (Next.js приложение)
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: production
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://localhost:8080
    ports:
      - "${CLIENT_PORT:-3000}:3000"
    depends_on:
      - nginx
    networks:
      - anime-network
    # Установка ограничений ресурсов для безопасности
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # Backend API сервер
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      ANILIBERTY_API_BASE: ${ANILIBERTY_API_BASE:-"https://anilibria.top/api"}
      REDIS_URL: ${REDIS_URL:-"redis://redis:6379"}
      DATABASE_URL: ${DATABASE_URL:-"postgresql://anime:animepass@postgres:5432/anime_db"}
      PROXY_WHITELIST: ${PROXY_WHITELIST:-"anilibria.top,anilibria.cc,cdn.anilibria.tv"}
      CORS_ALLOW_ORIGIN: ${CORS_ALLOW_ORIGIN:-"*"}
      JWT_SECRET: ${JWT_SECRET:-"your-super-secret-jwt-key"}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-"your-super-secret-refresh-key"}
      RATE_LIMIT_WINDOW_MS: ${RATE_LIMIT_WINDOW_MS:-900000}
      RATE_LIMIT_MAX_REQUESTS: ${RATE_LIMIT_MAX_REQUESTS:-100}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "${SERVER_PORT:-5000}:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - anime-network
    # Установка ограничений ресурсов для безопасности
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 1G
        reservations:
          cpus: '0.75'
          memory: 512M

  # Nginx reverse proxy
  nginx:
    # Используем конкретную версию вместо :latest для безопасности
    image: nginx:1.25.3-alpine3.18
    restart: unless-stopped
    ports:
      - "${NGINX_PORT:-8080}:80"
      - "${NGINX_HTTPS_PORT:-8443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - client
      - server
    networks:
      - anime-network
    # Установка ограничений ресурсов для безопасности
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M

  # HLS Media Server (для обработки видео)
  hls:
    # Используем конкретную версию вместо :latest для безопасности
    image: ant-media-server/ant-media-server-ce:2.5.1
    restart: unless-stopped
    ports:
      - "1935:1935"  # RTMP
      - "8080:8080"  # WebRTC
      - "8888:8888"  # HLS
    volumes:
      - hlsdata:/usr/local/antmedia/webapps/root
    networks:
      - anime-network
    # Установка ограничений ресурсов для безопасности
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G

volumes:
  pgdata:
    driver: local
  redisdata:
    driver: local
  hlsdata:
    driver: local

networks:
  anime-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
