auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

ruler:
  alertmanager_url: http://localhost:9093

# Конфигурация для сбора логов
ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 15m
  chunk_retain_period: 1m

# Конфигурация для хранения
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
    cache_ttl: 24h
    shared_store: filesystem
    index_directory: /loki/index
    index_queries_cache_config:
      cache:
        embedded_cache:
          enabled: true
          max_size_mb: 500

# Конфигурация для правил
ruler:
  storage:
    type: local
    local:
      directory: /loki/rules
  rule_path: /loki/rules-temp
  alertmanager_url: http://localhost:9093
  ring:
    kvstore:
      store: inmemory
    replication_factor: 1
  enable_api: true

# Конфигурация для запросов
query:
  max_retries: 10
  timeout: 2m

# Конфигурация для tenant
tenant_config:
  enabled: false

# Конфигурация для компактификации
compactor:
  working_directory: /loki/compactor
  shared_store: filesystem
  compactor_ring:
    kvstore:
      store: inmemory
    replication_factor: 1
  compactor_cache_config:
    cache:
      embedded_cache:
        enabled: true
        max_size_mb: 100
  max_retries: 10
  timeout: 2m

# Конфигурация для схемы
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
      chunks:
        period: 1h
      ruler:
        storage_type: local
        local:
          directory: /loki/rules