global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'anime-site-monitor'

# Правила для оповещений
rule_files:
  - "alert_rules.yml"

# Конфигурация сбора метрик
scrape_configs:
  # Prometheus сам
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Anime-site приложение
  - job_name: 'anime-site'
    static_configs:
      - targets: ['anime-site:3000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Node Exporter (системные метрики)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

  # Cadvisor (метрики контейнеров)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s

  # Blackbox Exporter (проверка доступности)
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://anime-site:3000
        - http://localhost:3000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Redis Exporter
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # MongoDB Exporter
  - job_name: 'mongodb-exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']
    scrape_interval: 30s

  # Nginx Exporter
  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx-exporter:9113']
    scrape_interval: 15s

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # MySQL Exporter
  - job_name: 'mysqld-exporter'
    static_configs:
      - targets: ['mysqld-exporter:9104']
    scrape_interval: 30s

  # VictoriaMetrics
  - job_name: 'victoria-metrics'
    static_configs:
      - targets: ['victoria-metrics:8428']
    scrape_interval: 15s

  # Loki
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    metrics_path: /metrics

  # Jaeger
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:16686']
    metrics_path: /metrics

  # Tempo
  - job_name: 'tempo'
    static_configs:
      - targets: ['tempo:3200']
    metrics_path: /metrics

  # OpenTelemetry Collector
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']
    scrape_interval: 15s

  # Consul
  - job_name: 'consul'
    static_configs:
      - targets: ['consul:8500']
    metrics_path: '/v1/agent/metrics'
    scrape_interval: 10s

  # Vault
  - job_name: 'vault'
    static_configs:
      - targets: ['vault:8200']
    metrics_path: '/v1/sys/metrics'
    scrape_interval: 30s

  # Zipkin
  - job_name: 'zipkin'
    static_configs:
      - targets: ['zipkin:9411']
    metrics_path: /metrics

  # Fluentd
  - job_name: 'fluentd'
    static_configs:
      - targets: ['fluentd:24224']
    metrics_path: /api/v1/metrics
    scrape_interval: 30s

  # Filebeat
  - job_name: 'filebeat'
    static_configs:
      - targets: ['filebeat:5066']
    metrics_path: /metrics
    scrape_interval: 30s

  # Logstash
  - job_name: 'logstash'
    static_configs:
      - targets: ['logstash:9600']
    metrics_path: /metrics
    scrape_interval: 30s

  # Kibana
  - job_name: 'kibana'
    static_configs:
      - targets: ['kibana:5601']
    metrics_path: /api/status
    scrape_interval: 30s

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: /_nodes/stats
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: /api/metrics
    scrape_interval: 30s

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 30s

# Конфигурация удаленных хранилищ
remote_write:
  - url: "http://victoria-metrics:8428/api/v1/write"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 10
      min_shard_duration_seconds: 60
      max_shard_duration_seconds: 0
      min_shard_size_bytes: 512
      max_shard_size_bytes: 104857600

# Конфигурация хранения
storage:
  tsdb:
    retention.time: 200h
    retention.size: 10GB